version: "3.9"

services:
  web:
    build: frontend/
    container_name: web
    volumes:
      - static:/udv-store/static
      - media:/udv-store/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  api:
    build: backend/
    container_name: api
    command: make static migrate up
    restart: always
    env_file:
      - backend/src/config/.env
    volumes:
      - static:/api/src/static
      - media:/api/src/media
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - backend/src/config/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  build:
  pgdata:
  static:
  media:
