# Generated by Django 3.2.12 on 2022-03-30 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='products')),
                ('description', models.CharField(max_length=5000)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Buying'), (2, 'Deposit'), (3, 'Coin Gifting')], default=1)),
                ('accural', models.FloatField()),
                ('description', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('destination_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to_me', to='api.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StorageCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.IntegerField(choices=[(1, 'Xs'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'Xl'), (6, 'Xxl'), (7, 'Xxxl')], default=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_in_storage', to='api.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Deliver'), (2, 'In Process'), (3, 'Done')], default=0)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_cell', models.ManyToManyField(related_name='related_orders', to='api.StorageCells')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_orders', to='api.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='FilesForTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='transaction_files')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='api.transactions')),
            ],
        ),
    ]
