# Generated by Django 3.2.12 on 2022-04-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterUniqueTogether(
            name='storagecell',
            unique_together={('product', 'size')},
        ),
    ]
