# Generated by Django 3.2.12 on 2022-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
