# Generated by Django 3.2.12 on 2022-04-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_profile_patronymic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="api.profile"),
        ),
    ]
