# Generated by Django 3.2.12 on 2022-04-06 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220404_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='profile',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination_user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to_me', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accrual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
