# Generated by Django 3.2.12 on 2022-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20220512_1703"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Transaction", "verbose_name_plural": "Transactions"},
        ),
    ]
