# Generated by Django 3.2.12 on 2022-07-07 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=1, max_digits=11, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="storagecell",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="accrual",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
