# Generated by Django 3.2.12 on 2022-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_coins_and_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
