# Generated by Django 3.2.12 on 2022-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_add_is_visible_into_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=1, max_digits=11)),
            ],
            options={
                "db_table": "activities",
            },
        ),
    ]
